package com.telerik.metadata.security.filtering.closure

import java.io.File

/**
 * Writes the retained set out as R8/ProGuard keep rules.
 *
 * Metadata and dex have to agree. Metadata says which classes JS can name; R8
 * decides which classes survive into the dex. Neither can see the other's
 * input -- R8 cannot read JS, and the metadata generator does not shrink code --
 * so the only way they stay consistent is to drive both from the same set.
 *
 * The rules keep, and nothing else: whatever the closure did not retain is left
 * for R8 to remove. So this file is what makes shrinking safe to turn on, not
 * an extra restriction on top of it.
 *
 * Members are kept wholesale for a retained class. Per-member rules would need
 * the JS side to have resolved every call exactly, and it cannot -- a computed
 * or reflective call names no member at all. Keeping all members of a class the
 * app can reach is the conservative half of that trade; the class-level strip
 * is where the size comes from.
 */
object ProguardRulesWriter {

    fun write(target: File, retainedClasses: Set<String>) {
        target.parentFile?.mkdirs()

        target.bufferedWriter().use { out ->
            out.write(
                    """
                    # GENERATED by the NativeScript metadata generator. Do not edit.
                    #
                    # Keeps every class reachable from JS, as computed by
                    # MetadataClosure from the app's own bundle. Classes absent
                    # here are absent from the metadata too, so JS cannot name
                    # them and R8 is free to remove them.
                    #
                    # Regenerate by rebuilding.

                    """.trimIndent()
            )
            out.newLine()

            /* The runtime reaches these by name from native code, so no static
             * analysis of either side can see the reference. */
            out.write(
                    """
                    -keep class com.tns.** { *; }
                    -keep class **.R$* { *; }
                    -keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*

                    # Shrink, but do not rename. Every lookup this runtime makes
                    # is by name: metadata names classes, and JS names them
                    # through it. A -keep rule preserves the names of classes it
                    # matches, but R8 still renames the synthetic classes it
                    # generates itself -- desugaring moved a static interface
                    # method into StaticProducer${'$'}-CC and R8 emitted it as B.a,
                    # which the runtime then could not find. Renaming buys some
                    # string space; removing unreachable classes is where the
                    # size comes from, and that still happens.
                    -dontobfuscate

                    # Below minSdk 24 a static interface method cannot live on
                    # the interface, so desugaring moves the body into a
                    # synthetic companion -- ${'$'}-CC for D8/R8, ${'$'}${'$'}CC for Bazel. The
                    # runtime tries the interface and both companion names in
                    # turn (JEnv::GetInterfaceStaticMethodIDAndJClass), so all
                    # three have to survive. Nothing in Java calls them, so
                    # without this R8 removes every one: measured, 18 companion
                    # classes went to 0 and three specs failed with
                    # "Could not call static interface method".
                    -keep class **${'$'}-CC { *; }
                    -keep class **${'$'}${'$'}CC { *; }
                    -keepclassmembers interface * { public static <methods>; }

                    """.trimIndent()
            )
            out.newLine()

            for (name in retainedClasses.sorted()) {
                /* $ separates nested classes in the binary name and is also
                 * ProGuard's own wildcard-free separator -- it needs no
                 * escaping, but the name must not be split on it either. */
                out.write("-keep class $name { *; }")
                out.newLine()
            }
        }
    }
}
